#Use una imagen base de Python oficial como padre
FROM python:3.11-slim-buster

#Establece el directorio de trabajo en /app
WORKDIR /app

ADD  .app /app/

#Instala cualquier paquete necesario
RUN pip install --no-cache-dir -r requirements.txt

#Haz que el puerto 5000 esté disponible fuera del contenedo
EXPOSE 5000


#Ejecuta app.py cuando se inicia el contenedor
CMD [ "python","app.py" ]